### PR TITLE
Us1 Modules Verification

### PR DESCRIPTION
**Pull request by milosmihajlovic91**
Let me know if its good

### CODE REVIEW

**Review by EkaterinaKit — APPROVED** [review]
Look great!

**Review by EkaterinaKit — APPROVED** [review]
Keep great work!

**Review by EkaterinaKit — APPROVED** [review]
NICE!

**Review by opylypenko2 — COMMENTED** [review]
Looks good!

**Review by opylypenko2 — APPROVED** [review]

**Pull request closed without merging**
